### ISSUE TITLE
pool overflow and other SQLA goodies

### ISSUE THREAD

**Issue by tarekziade** [mozilla-services/cliquet#186]
we should add overflow in our pool, plus more goodies from SQLA

- overflow
- max backlog while waiting for a connection from the pool.
- pool recycling

see http://docs.sqlalchemy.org/en/rel_0_9/core/pooling.html

**Comment by leplatrem** [comment]
What I really about SQLA API is proxied pool activation: 

```python
import sqlalchemy.pool as pool
import psycopg2 as psycopg

psycopg = pool.manage(psycopg)
```

That way we could setup the pooling of our choice in the projects using cliquet, instead of growing cliquet code base with more features (or worse, adding SQLA as a dependency).

Even if I completely agree that the current implementation is rather stupid and limited, I'm not a fan of reimplementing complex connection pooling features in python. *pgBouncer* and *pgPool* are the tools of reference and would prefer to rely on them...

**Comment by leplatrem** [comment]
Some notes: 

* https://github.com/mozilla-services/server-syncstorage/blob/1.5.11/syncstorage/storage/sql/dbconnect.py
* https://docs.sqlalchemy.org/en/latest/core/pooling.html#connection-pool-configuration
* https://bugzilla.mozilla.org/show_bug.cgi?id=692383
* https://bugzilla.mozilla.org/show_bug.cgi?id=750964
* https://github.com/mozilla-services/server-syncstorage/commit/f93ca85a985364f123ad79cbdc2fcc29c5656586

```
pool_size = <%= @pool_size %>
pool_max_overflow = <%= @pool_max_overflow %>
pool_max_backlog = <%= @pool_max_backlog %>
pool_recycle = <%= @pool_recycle %>
```
