### ISSUE TITLE
Clarify PUT-after-DELETE behavior

### ISSUE THREAD

**Issue by michielbdejong** [mozilla-services/cliquet#249]
What happens if I create a resource, then delete it, and then send a PUT request to the id of the deleted record, with a `If-Unmodified-Since` header of before the deletion time?

Will the server keep a 'tombstone' for each resource that ever existed, documented when it was deleted for the last time? If the server runs for many years, will this history of tombstones ever be truncated?

It might be worth documenting this in http://cliquet.readthedocs.org/en/latest/api/resource.html#put-collection-id or elsewhere (couldn't find anything about this edge-case).

**Comment by leplatrem** [comment]
You are completely right, this edge case is not explicited anywhere.

Indeed, we keep "tombstones" as tuples *(user_id, collection_id, record_id, last_modified)*.

In the current code, we check the ``If-Unmodified-Since`` only against existing records. Hence, I believe that we should consider your feedback as a bug report: if the record is missing we should check the potential tombstone !

In regards to accumulation of tombstones, we don't see it as a real problem since it is pretty cheap. However we had in mind a "purge" command [0].

    cliquet --ini server.ini purge userid=mat collection=articles before=1430994615816

I haven't check the current behaviour of the implementation, but it would be sound to be able to purge from the collection endpoint using:

    DELETE /collections/articles?deleted=true

Thanks for spotting this !

[0] Originally mentioned in the ReadingList project (API built using Cliquet) https://github.com/mozilla-services/readinglist/issues/181
