### ISSUE TITLE
Use peep rather than pip for packaging dependencies

### ISSUE THREAD

**Issue by ametaireau** [mozilla-services/cliquet#273]
We should use [peep](https://pypi.python.org/pypi/peep/) with hashes rather than pip directly to get our dependencies.

> Deploying Python projects has long been a source of frustration for the security-conscious: a compromise of PyPI or its third-party CDN could get you a package different from the one you signed up for.

**Comment by Natim** [comment]
The current version of pypi prevent user for updating again a removed file while they have the same name.
Also we are using semver version pinning ``ie cliquet>=2.10,<2.11`` where peep will not be useful.

Closing for now, feel free to reopen if you think it worth it nevertheless.

**Comment by ametaireau** [comment]
The approach Peep has is approximately similar to what the SRI does for HTML assets. It's about trust: here you are forced to trust PyPI to be distributing the right files.

But I agree, we should be pinning the dependencies, which we currently don't do, in the setup.py. Peep sounds like something we would like to use for deploying Kinto rather than for releasing Cliquet.

**Comment by Natim** [comment]
Actually we are already pinning for Kinto and we are building a Known Good Set requirements file for both Cliquet and Kinto. Maybe we should use peep to build this version KGS file.

**Comment by Natim** [comment]
Ok I tried and I've got: ``TypeError: __init__() got an unexpected keyword argument 'use_wheel'``

**Comment by ametaireau** [comment]
I'm actually unsure what the value is for peep here for our users, since they only use the `requirements.txt` when developing (otherwise, they do "pip install kinto", and don't use the requirements file).

Summoning @erikrose for more insights here.

**Comment by erikrose** [comment]
Sorry, this got pushed way down into the murky depths of my mailbox. @almet is right: peep is useful mostly for artifacts that will be deployed. Typically, the top-level artifact has a requirements.txt that is flattened out, including all subdependencies recursively, and then one applies peep hashes to that to ensure repeatability and keep malicious code off servers. Putting hashes in a reqs.txt for a library like Cliquet is a niche-ier use case, one I've never felt the need for.

I have opinions on the semantics of setup.py and reqs.txt pinnings as well, which you're welcome to: I like setup.py to specify the widest range of compatible versions known to work. I never pin to a specific version, except maybe 0.x releases that may break backward compatibility before 1.0. This way, attempts to use the library with other code that may require (for example) 1.0.2 rather than 1.0.1 don't end in unresolvable conflicts. Conversely, I use reqs.txt as a KGS, so generally everything is pinned. These conventions are pretty widespread, though some people I think highly of have argued with me over them. :-) Cheers!
