### ISSUE TITLE
Add cache headers

### ISSUE THREAD

**Issue by tarekziade** [mozilla-services/cliquet#401]
We will use Kinto behind a proxy cache for Go Faster on all GETs.

In order to do this we need to implement a few headers:  Expires & Cache-Control.

We're probably going to use Nginx as a cache server - since it's already our proxy. 

So this link http://wiki.nginx.org/NginxHttpProxyModule#proxy_cache is a good reading to implement the cache headers. 

This page is also cool to understand how to set up nginx as a proxy cache : https://serversforhackers.com/nginx-caching

**Comment by Natim** [comment]
Isn't ETag enough for that?

**Comment by Natim** [comment]
Apparently not, see http://stackoverflow.com/questions/499966/etag-vs-header-expires

**Comment by tarekziade** [comment]
@Natim read the links I added, it explains well

**Comment by tarekziade** [comment]
For the configuration, I propose that Kinto provide a global set of options and per-bucket options to define the max age value of a collection.

By default, Kinto would set a "Cache-Control: no-cache" header for everything.

**Comment by Natim** [comment]
I discussed that with @tarekziade and we have use-cases where we know that an update per day is enough and that the proxy should not call the Kinto server more than once a day for a specific collection.

To begin with a configuration endpoint that could define the Cache-Expire value for a given collection would be enough.

This value should define two headers:

### If deactivated:

 - ``Cache-Control: no-cache``
 - ``Expire`` current server date

### If activated

 - ``Cache-Control: max-age=<number of seconds>``
 - ``Expire`` expiration date

It is interesting to note that the client can also send a ``Cache-Control`` header to force refresh.

See http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.9 for more information.

**Comment by ametaireau** [comment]
Thanks for starting this discussion! In order to explicitly state the problem we are trying to solve, here is some more context:

For the go-faster project, a set of [kinto collections](http://kinto.readthedocs.org/en/latest/concepts.html#buckets-collections-and-records) will be used to publish updates to the User-Agents (Firefox instances) out in the wild.

This data is globally shared and all the client will only have read access to it. Rather than requesting the data to Kinto at each request, it might make sense to cache Kinto's response.

The clients, in order to retrieve the latest data, will issue a `GET /buckets/{bid}/collections/{cid}/records?_since={timestamp}` as described in the (polling for change section)[http://kinto.readthedocs.org/en/latest/api/synchronisation.html#polling-for-changes] of the docs.

Each time the collection is updated, the cache should be invalidated, and eventually recreated. We could use the Kinto notification system in order to ping the caching layer.

With this in mind, I looked at the documents you pointed out Tarek (thanks!). I don't see any way to invalidate the cache in there, tough.

Before digging more in the details of caching, I think we should ensure a few things:

Do we need to invalidate the cache just after a database update? If not, we might just wait for a specific period and let the cache expire, and the origin server being called again;

Is NGINX the caching layer we will use in production? (hi @micheletto, @deanwilson)

**Comment by Natim** [comment]
> Do we need to invalidate the cache just after a database update?

This is the question we discussed with @tarekziade this morning, and the answer was no, for certain collection, we can do the update and wait for the cache to invalidate itself. (After 20h or a day for instance)

**Comment by ametaireau** [comment]
Okay so this might just be enough :-)

**Comment by leplatrem** [comment]
In the initial discussions, we were wondering if it was relevant to handle this in the application, or rely on an external service like Varnish.

I believe we now agree to implement basic headers management in the application. 

From what I read here, the configuration could happen at two levels, from ``ini`` file or via the bucket/collection metadata (JSON API). 
Cliquet might be the right place to implement the ini part, but it does not manipulate bucket/collections notions for the metadata part. That would have to be implemented in Kinto.

I'll start something :)

> Note:
> If someday the cache needs to be invalidated on record update, #32 may help (triggering events)...
