### ISSUE TITLE
Rename BaseResource and ProtectedResource ?

### ISSUE THREAD

**Issue by leplatrem** [mozilla-services/cliquet#439]
Currently : 

* BaseResource isolates records by user
* ProtectedResource adds permissions management via ``"permissions"`` attribute in payloads

I propose that we rename them:

*  ``UserResource``, whose records are isolated by user
* ``PermissionResource`` ? ``SharableResource`` ? ``ProtectedResource`` ?
* Add ``GlobalResource``, whose records are the same for any user

Any thoughts ?

**Comment by ametaireau** [comment]
`UserResource` and `ShareableResource` seems good choices to me.

**Comment by ametaireau** [comment]
I'm not sure about the need for `GlobalResource`. If we decide to go for it, then we should use `ShareableUserResource` rather than `ShareableResource` then.

**Comment by MrChoclate** [comment]
`UserResource` is in my opinion a better name than BaseRessource as only one principal can manipulate them.
`SharableResource` sounds better than `ProtectedResource` because `ProtectedResource` appears to be more strict whereas (if I understood correctly) it is meant to open permissions. I cannot find a use case where a `ProtectedRessource` would have less permissions (more strict) than a `BaseRessource`

> ProtectedResource adds permissions management via "permissions" attribute in payloads

You should definitely add this sentence to the doc.
