### ISSUE TITLE
Permissions more explicit documentation

### ISSUE THREAD

**Issue by MrChoclate** [mozilla-services/cliquet#543]
I have a problem with the documentation of permissions.

After reading the doc several times I still get the following questions:
Is the permission_backend set by default? How to set it on .ini file?
How do you change permissions? `<resource_name>_<permission>_principals` but how with the permission_backend? Once you did it, is there a way to save it and version it?

By default all the records can only be seen by the principal who created it, how to made all records public? I tried adding `champions_read_principals = system.Everyone` in my .ini but it did not work.

Is it possible to hide a field of a record according to permissions? (in the case you made all records public)

```python

class ChampionSchema(resource.ResourceSchema):
    # Only author can see this or only this principals...
    secret = colander.SchemaNode(colander.String())
    name = colander.SchemaNode(colander.String())
```

When we get /collections we got:
> permissions: optional a json dict containing the permissions for the collection of records.

What does optional means? When do we got it?

**Comment by leplatrem** [comment]
> I have a problem with the documentation of permissions.

Thanks for this feedback ! ...and your patience !

> Is the permission_backend set by default? How to set it on .ini file?

Nope, like storage, you need to at least define `cliquet.permission_backend` and `cliquet.permission_url` settings.

> How do you change permissions?

Permissions can be changed on records by those who have write access (ie. creator of record, or principals mentioned in `resource_name>_write_principals`)

> how to made all records public?

`champion_read_principals = system.Everyone` should work (careful about singular in resource name)

However (*and the documentation might be really bad about this*), you have to use a `ProtectedResource` and a `RouteFactory`

You can find an example here :  https://github.com/mozilla-services/cliquet/blob/118d1235a309f19616386f36c3ca2c58ef491c07/cliquet/tests/testapp/__init__.py#L15

> Is it possible to hide a field of a record according to permissions?

Yes, with some hacks... overriding the resource class:

(*untested*)

```python
class HiddenFields(ProtectedResource):
    def postprocess(self, *args, **kwargs):
        result = super(HiddenFields, self).postprocess(*args, **kwargs)
        if self.request.prefix_authenticated_id:
            return result
        if isinstance(result['data'], list):
            # collection endpoint.
            for record in result['data']:
                record.pop('secret', None)
        else:
            result['data'].pop('secret', None)
        return result

    def _raise_412_if_modified(self, record=None):
        if record and not self.request.prefix_authenticated_id:
            record.pop('secret', None)
        return super(HiddenFields, self)._raise_412_if_modified(record)
```

> When we get /collections we got: permissions: optional a json dict containing the permissions for the collection of records

You are right, this is wrong. Permissions are only provided on single record endpoints with the current code.

* Related #439

**Comment by MrChoclate** [comment]
> cliquet.permission_url

If I use memory I guess this is not required?

> However (and the documentation might be really bad about this), you have to use a ProtectedResource and a RouteFactory

Well I was missing this information.

> Yes, with some hacks... overriding the resource class:

Thanks I will try it later.

> Permissions are only provided on single record endpoints with the current code.

Things are getting confused. We have permissions on record and on collections, right?

With ```champion_read_principals = system.Everyone``` everyone can see every records when they do GET /champions. Who can read records of this collection? Owner, everyone? (Who can do GET /champions/id ?) Is there some kind of inheritance? When I create a new record, what are the default permission on this record? Is there a way to change this default?

For example I want all my users to see all champions (/champions) but they can only get their own records with /champions/id. A use case could be that `collection_get()` is override to hide a field so we do  not have:
```python
collection_get() == [get() for x  in collection]
```

**Comment by Natim** [comment]
> If I use memory I guess this is not required?

If you don't specify it it will just deactivate the backend so even with memory you have to specify it.
Also I wouldn't use Memory because it doesn't save your permission on server or worker restart. You should use at least the same as your storage backend. (So if you use Memory for storage you can use it as well for permission)

With Cliquet there are no inheritance by default, you must provide a inheritance function.
See for instance what we did for Kinto here: https://github.com/Kinto/kinto/blob/master/kinto/authorization.py

**Comment by Natim** [comment]
Can you show us an example of the collection_get and get() result?

**Comment by leplatrem** [comment]
>> cliquet.permission_url
> 
> If I use memory I guess this is not required?

For memory, it can be ignored indeed (@Natim got confused with `cliquet.permission_backend`)
But he is right about not using it in production :)

>> However (and the documentation might be really bad about this), you have to use a ProtectedResource and a RouteFactory
>
> Well I was missing this information.

I am sorry, my turn to be wrong. This is not mandatory actually, I just realized that we set it up automatically [when the protected resource is registered](https://github.com/mozilla-services/cliquet/blob/master/cliquet/resource/viewset.py#L206-L209).

>> Permissions are only provided on single record endpoints with the current code.
> 
> Things are getting confused. We have permissions on record and on collections, right?

Yes. But the `permissions` attribute is only present in the payloads of the record endpoints (doc is wrong, I will work on it). That means that permissions management via JSON API is only available at the record level.
The permissions management at the collection level is done using settings in configuration.

> With champion_read_principals = system.Everyone everyone can see every records when they do 
> GET /champions. Who can read records of this collection?

If everyone can read the collection, everyone can read every records of the collection. Every one can `GET /champions/id`. This is a kind of inheritance yes.

What we also provide by default, is the ability to only see the records where you have read access.
For example, in the configuration, you only set `champion_write_principals = system.Authenticated`. Thus everyone can create records. And when they `GET /champions` they only see the records where they have read permissions (the ones they created, or that someone shared with them, or shared with system.Authenticated/Everyone...)

> When I create a new record, what are the default permission on this record?

The default permission is `{"write": ["<current user-id>"]}`. (*and write includes read*)

> Is there a way to change this default?

By inheriting the classes in `cliquet/resource` and plugging them yes. We would be very happy if you contribute something to adjust default permissions without overriding classes :)

> For example I want all my users to see all champions (/champions) but they can only get their own
> records with /champions/id. 

Ok, that's because of your secret fields, right ? You want everyone to be able to list every records and their *public* fields. But when they get a single record they can see the *private* fields if the record belongs to them.

That is feasible indeed but you have to inherit and customize the behaviour when returning payloads. It is not covered by our code currently. Or using two resources maybe...  `GET /champions-secret?rel_record=abcd-5678-3090`

> With Cliquet there are no inheritance by default, you must provide a inheritance function.
> See for instance what we did for Kinto here: https://github.com/Kinto/kinto/blob/master/kinto/authorization.py
> 
I don't think this is your use-case. That's when you have several resources and want to give permissions to one from the permissions you have on the others. In Kinto we use it to have like cascading permissions...

Thank you very much for all these questions ! It really helps us to realize how poorly this is documented :) Thank you again for your patience, you're enduring early problems, we will work on it !

**Comment by Natim** [comment]
> The default permission is {"write": ["<current user-id>"]}. (and write includes read)

It is the case for kinto but I do not think it is the default for cliquet.
you need to define a ``get_bound_permissions`` method that return the list of permission names to take into account for permission inheritance.

It is a simpler implementation of https://github.com/Kinto/kinto/blob/master/kinto/authorization.py#L110-L138

And then plugged into the AuthorizationPolicy like that: https://github.com/Kinto/kinto/blob/master/kinto/authorization.py#L148-L151

**Comment by MrChoclate** [comment]
So I set up my .ini with this:
```
cliquet.cache_backend = cliquet.cache.memory
cliquet.storage_backend = cliquet.storage.redis
cliquet.permission_backend = cliquet.permission.redis

cliquet.champion_read_principals = system.Everyone
cliquet.champion_write_principals = system.Everyone
cliquet.champion_create_principals = system.Everyone
```
That sounds like I give all power to everyone. And there is data persistence so redis should be well configured.

I used ProtectedRessource and added RootFactory.
I created a few record with user:pass
```
http  127.0.0.1:6543/v0/champions --auth user:pass
{
    "data": [
        {
            "file": "filedata2",
            "id": "a03e67d1-5ec9-4632-afae-ba7f363e6712",
            "last_modified": 1446633072611,
            "name": "myname2",
            "status": "pending"
        },
        {
            "file": "filedata2",
            "id": "19dc04b5-de02-4f75-97ee-7354681efc1b",
            "last_modified": 1446632275703,
            "name": "myname2",
            "status": "pending"
        },
        {
            "file": "filedata",
            "id": "064793b6-5dc5-4fce-b965-5517ea61df05",
            "last_modified": 1446632261072,
            "name": "myname",
            "status": "pending"
        }
    ]
}
```

Then  I was expecting that all user could see this. But with another principal I got no data:
```
 http  127.0.0.1:6543/v0/champions --auth user:pas
{
    "data": []
}
```

Then I looked at record permission and tried adding read permission.
```
echo '{"permissions": {"read": ["system.Everyone"]}}' | http PATCH 127.0.0.1:6543/v0/champions/a03e67d1-5ec9-4632-afae-ba7f363e6712 --auth user:pass 
{
    "data": {
        "file": "filedata2",
        "id": "a03e67d1-5ec9-4632-afae-ba7f363e6712",
        "last_modified": 1446633693760,
        "name": "myname2",
        "status": "pending"
    },
    "permissions": {
        "read": [
            "system.Everyone"
        ],
        "write": [
            "basicauth:5741b99cc5b467903f9a392b092d59f6d227354acbca1834bdd1dea1dd350a8e"
        ]
    }
}
```

I still cannot see it with another principal using /champions or /champions/a03e67d1-5ec9-4632-afae-ba7f363e6712

**Comment by leplatrem** [comment]
> I still cannot see it with another principal 

Good news, you found a bug :) https://github.com/mozilla-services/cliquet/issues/549
