### ISSUE TITLE
Some items are included multiple times when iterating on a paginated list

### ISSUE THREAD

**Issue by almet** [mozilla-services/cliquet#588]
When writing [the kinto.py client](https://github.com/kinto/kinto.py), I found that some items are returned multiple times when paginating a list of records.

This happens at least with the memory and redis backends.

**Comment by leplatrem** [comment]
As far as I understood, it is due to default sorting on `-last_modfied` when records have duplicate timestamps.

With postgresql the integrity constraints prevents those duplicates. It would be interesting to describe a procedure to reproduce this bug.
Especially because this test asserts it works: https://github.com/mozilla-services/cliquet/blob/2.11.0/cliquet/tests/resource/test_pagination.py#L75-L77
