### ISSUE TITLE
Document how to create a working dev environment

### ISSUE THREAD

**Issue by ametaireau** [mozilla-services/cliquet#65]
Especially for FxA

**Comment by hiromipaw** [comment]
Hi,
Since I would be very keen to start contributing to this project I could try to work on this as a first issue, if you haven't already started. Please let me know what you think. 

On a side note I am not sure you have a better place where to ask such questions. So if I am polluting your issues list I apologise in advance.

:)

**Comment by ametaireau** [comment]
I was just about to take this over, but I believe that's a good place to start yeah!

You can come over on #storage on the mozilla irc network if you are looking for help / discussions, we'll be there (I actually just created the channel).
